language: python
cache:
  directories:
  - $HOME/.cache/pip
  - $HOME/.nvm
  - node_modules
  - wger/node_modules
sudo: false
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
env:
- TEST_MOBILE=True  DB=postgresql TRAVIS_NODE_VERSION="4"
- TEST_MOBILE=True  DB=sqlite     TRAVIS_NODE_VERSION="4"
- TEST_MOBILE=False DB=postgresql TRAVIS_NODE_VERSION="4"
- TEST_MOBILE=False DB=sqlite     TRAVIS_NODE_VERSION="4"
install:
- curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.4/install.sh | METHOD=script
  bash
- . $HOME/.nvm/nvm.sh
- nvm install $TRAVIS_NODE_VERSION
- nvm use $TRAVIS_NODE_VERSION
- pip install -r requirements_devel.txt
- npm install
- if [[ "$DB" = "postgresql" ]]; then pip install psycopg2; fi
- if [[ "$DB" = "sqlite" ]]; then invoke create_settings; fi
- if [[ "$DB" = "postgresql" ]]; then invoke create_settings --database-type postgresql;
  fi
before_script:
- if [[ "$DB" = "postgresq" ]]; then psql -c 'DROP DATABASE IF EXISTS test_wger;'
  -U postgres; fi
- if [[ "$DB" = "postgresql" ]]; then psql -c 'CREATE DATABASE test_wger;' -U postgres;
  fi
script:

# Formatting
- pep8 wger

# Javascript linting
- gulp lint

# Regular application
- coverage run --source='.' ./manage.py test --parallel

# Code coverage
- coverage report
deploy:
  provider: heroku
  api_key:
    secure: WATuvOwnsrRm4UvK3bvwhSesOIjP2EOCrKuUDCrxBN6iEeuS3RCXI1OSvzQlHwFxyu59P3mFJZPha9HwD9wq37XzkEQhrE8iWN+NtJkvIl2qTGW12HoBmMGJClvvfMwiGCalat6su21cOHgHk+pb14vOwqLvK6rTruIg6ewOi7bbOoLn/PyTLOn0aaXs1k/JruFy40gvxonnNoERqnELwvFA9QbrrSlHoSM2OnxpUIkZdpqIITau7WhIh0rTvT0GJRPrCJ0q9g4W/+IhGzCrDcKvcl5CsntWx6aydyT+l/A/ZZDXVU69SNrx7SNxhIQhtmb5I2+dHKPtS8FlDh0KwWo2DKKLjMjQ/XceV2Stb26Jbve0yUs2hcdDTJgn/MvwSU4v38Ptd9hgYTPpsImNAwMp2G2UebrlsqS8TdoGnpHEf1Yrs0pJNHTOnq3HXU7xKTMoRR07UbjzQhGxMmX6LevBBubrI9M5rho9dT2KQ0cZWvMHoXzdEhGVZ0VEsfyToKmFGYmcbmbpWMr9D6vM1D91T0NoBrA9mWPcHR81ZvRfRkkV+qpKorT7q+rqVwnCjlSlb7UBl8NPCb65L8d3K/1zIYhzT7evoiMgs5bFKauDKRFSTYmH9RlsTm1acW3eeiZAiiHEh1woXTmjfH1fH3ZA79h3+M8JaTy6le3oKWk=
  app: wgervulcan
  on:
    repo: andela/wger_vulcan

#Send notifications to slack
notifications:
  slack: andela:qcESb11tbSzWp8SiteRorMkQ
  
 #Coveralls
after_success:
- coveralls
