version: "3"
services:

  wger:
    image: mbarakmbigo/wger_vulcan
    ports:
      - 5000:80
    networks:
      - frontend
      - backend
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure



networks:
  frontend:
  backend:
