# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-10 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20170330_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nonsense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default=2)),
            ],
        ),
    ]
