# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-25 14:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_fitbitappdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFitBitDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=400, unique=True)),
                ('refresh_token', models.CharField(max_length=400, unique=True)),
                ('enabled_fitbit', models.BooleanField(default=False)),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFitBitScope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.BooleanField(default=False)),
                ('heartrate', models.BooleanField(default=False)),
                ('location', models.BooleanField(default=False)),
                ('nutrition', models.BooleanField(default=False)),
                ('profile', models.BooleanField(default=False)),
                ('settings', models.BooleanField(default=False)),
                ('sleep', models.BooleanField(default=False)),
                ('social', models.BooleanField(default=False)),
                ('weight', models.BooleanField(default=False)),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
