# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-19 13:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20170411_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermetadata',
            name='can_create_users',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usermetadata',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
