# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-26 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_userfitbitdetails_fitbit_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfitbitdetails',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserFitBitDetails',
        ),
    ]
