# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-26 09:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0014_auto_20170426_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFitBitDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=400, unique=True)),
                ('access_token', models.CharField(max_length=400, unique=True)),
                ('refresh_token', models.CharField(max_length=400, unique=True)),
                ('enabled_fitbit', models.BooleanField(default=False)),
                ('wger_user_id', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
