# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-27 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_userfitbitdetails_expires_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfitbitdetails',
            name='expires_in',
            field=models.DateTimeField(),
        ),
    ]
