# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-27 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20170427_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfitbitdetails',
            name='expires_in',
        ),
    ]
