# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-27 12:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_userfitbitdetails_expires_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfitbitdetails',
            name='expires_in',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 27, 12, 8, 11, 573331, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
