# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-02 07:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_userfitbitdetails_expires_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfitbitdetails',
            name='expires_in',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 2, 10, 25, 33, 994920)),
        ),
    ]
