# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-02 07:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20170502_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfitbitdetails',
            name='expires_in',
        ),
    ]
