# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-07 12:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_auto_20170423_0247'),
        ('manager', '0009_auto_20170507_1314'),
    ]

    operations = [
    ]
